# Generated by Django 5.1.7 on 2025-03-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pessoas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pessoa",
            name="altura",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="pessoa",
            name="sexo",
            field=models.CharField(
                choices=[("M", "Masculino"), ("F", "Feminino")], max_length=1
            ),
        ),
    ]
